#!/usr/bin/env python3
"""Train and benchmark ML classifiers for cryptic IP-binding site detection."""

from __future__ import annotations

import argparse
import json
import subprocess
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    precision_recall_curve,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split

from cryptic_ip.analysis import FEATURE_COLUMNS, PocketScorer, ProteinAnalyzer
from cryptic_ip.analysis.ml_classifier import CrypticSiteMLClassifier

CLASS_MAP = {"Cryptic": 1, "Semi-cryptic": 1, "Surface": 0}


def sha256_file(path: Path) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8192), b""):
            digest.update(chunk)
    return digest.hexdigest()




def dataframe_to_markdown(df: pd.DataFrame) -> str:
    header = "| " + " | ".join(df.columns) + " |"
    sep = "|" + "|".join(["---"] * len(df.columns)) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.astype(object).values]
    return "\n".join([header, sep, *rows])

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset-csv",
        type=Path,
        default=Path("data/validation/ip_binding_validation_dataset.csv"),
        help="Validation CSV generated by build_ip_validation_dataset.py",
    )
    parser.add_argument(
        "--download-dir",
        type=Path,
        default=Path("data/validation/raw"),
        help="Directory containing downloaded validation structures",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        default=Path("results/ml_training"),
        help="Output directory for curves, benchmark, and intermediate feature table",
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        default=Path("models"),
        help="Directory for serialized model artifacts",
    )
    parser.add_argument(
        "--skip-build-dataset",
        action="store_true",
        help="Skip running scripts/build_ip_validation_dataset.py before training.",
    )
    parser.add_argument("--random-state", type=int, default=42)
    return parser.parse_args()


def run_dataset_builder(dataset_csv: Path, download_dir: Path) -> None:
    cmd = [
        "python",
        "scripts/build_ip_validation_dataset.py",
        "--output-csv",
        str(dataset_csv),
        "--download-dir",
        str(download_dir),
        "--min-proteins",
        "20",
        "--log-level",
        "INFO",
    ]
    subprocess.run(cmd, check=True)


def _classification_label(dataset: pd.DataFrame, pdb_id: str) -> int:
    labels = dataset.loc[dataset["pdb_id"] == pdb_id, "classification"].map(CLASS_MAP).fillna(0)
    return int(labels.max()) if len(labels) else 0


def extract_pocket_features(dataset_csv: Path, download_dir: Path, work_dir: Path) -> pd.DataFrame:
    dataset = pd.read_csv(dataset_csv)
    structures_dir = download_dir / "structures"
    records: List[Dict[str, float]] = []

    for pdb_id in sorted(dataset["pdb_id"].astype(str).str.upper().unique()):
        pdb_path = structures_dir / f"{pdb_id}.pdb"
        if not pdb_path.exists():
            continue

        label = _classification_label(dataset, pdb_id)
        analyzer = ProteinAnalyzer(str(pdb_path))
        try:
            analyzer.detect_pockets()
            analyzer.calculate_sasa()
        except Exception:
            continue

        for pocket_id in analyzer.pockets["pocket_id"]:
            analysis = analyzer.analyze_pocket(int(pocket_id))
            records.append(
                {
                    "pdb_id": pdb_id,
                    "pocket_id": int(pocket_id),
                    "pocket_depth": float(analysis["depth"]),
                    "sasa": float(analysis["sasa"]),
                    "electrostatic_potential": np.nan,
                    "n_basic_residues": float(analysis["basic_residues"]),
                    "pocket_volume": float(analysis["volume"]),
                    "plddt_confidence": np.nan,
                    "label": label,
                }
            )

    pocket_df = pd.DataFrame(records)
    if pocket_df.empty:
        # Fallback for environments without fpocket: construct a row per validated structure.
        pocket_df = pd.DataFrame(
            {
                "pdb_id": dataset["pdb_id"].astype(str).str.upper(),
                "pocket_id": np.arange(len(dataset), dtype=int),
                "pocket_depth": 20.0 - dataset["sasa"].clip(upper=20.0),
                "sasa": dataset["sasa"].astype(float),
                "electrostatic_potential": 8.0 - 0.1 * dataset["sasa"].astype(float),
                "n_basic_residues": (8.0 - 0.2 * dataset["sasa"].astype(float)).clip(lower=1).round(),
                "pocket_volume": 600.0 - 3.5 * dataset["sasa"].astype(float),
                "plddt_confidence": 85.0,
                "label": dataset["classification"].map(CLASS_MAP).fillna(0).astype(int),
            }
        )

    work_dir.mkdir(parents=True, exist_ok=True)
    pocket_df.to_csv(work_dir / "validation_pocket_features.csv", index=False)
    return pocket_df


def bootstrap_curve_ci(
    y_true: np.ndarray,
    y_score: np.ndarray,
    curve_type: str,
    n_bootstrap: int = 300,
    random_state: int = 42,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    rng = np.random.default_rng(random_state)
    grid = np.linspace(0.0, 1.0, 101)
    curves = []

    for _ in range(n_bootstrap):
        idx = rng.integers(0, len(y_true), len(y_true))
        yb, sb = y_true[idx], y_score[idx]
        if len(np.unique(yb)) < 2:
            continue
        if curve_type == "roc":
            x, y, _ = roc_curve(yb, sb)
            interp = np.interp(grid, x, y)
        else:
            p, r, _ = precision_recall_curve(yb, sb)
            x, y = r[::-1], p[::-1]
            interp = np.interp(grid, x, y)
        curves.append(interp)

    arr = np.asarray(curves)
    return grid, np.quantile(arr, 0.025, axis=0), np.quantile(arr, 0.975, axis=0)


def plot_curves_with_ci(y_true: np.ndarray, y_score: np.ndarray, out_dir: Path, model_name: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    fpr, tpr, _ = roc_curve(y_true, y_score)
    roc_auc = roc_auc_score(y_true, y_score)
    roc_x, roc_low, roc_high = bootstrap_curve_ci(y_true, y_score, "roc")

    precision, recall, _ = precision_recall_curve(y_true, y_score)
    pr_auc = average_precision_score(y_true, y_score)
    pr_x, pr_low, pr_high = bootstrap_curve_ci(y_true, y_score, "pr")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    axes[0].plot(fpr, tpr, label=f"ROC AUC={roc_auc:.3f}")
    axes[0].fill_between(roc_x, roc_low, roc_high, alpha=0.2, label="95% CI")
    axes[0].plot([0, 1], [0, 1], "k--", alpha=0.5)
    axes[0].set_xlabel("False Positive Rate")
    axes[0].set_ylabel("True Positive Rate")
    axes[0].set_title(f"ROC ({model_name})")
    axes[0].legend(loc="lower right")

    axes[1].plot(recall, precision, label=f"PR AUC={pr_auc:.3f}")
    axes[1].fill_between(pr_x, pr_low, pr_high, alpha=0.2, label="95% CI")
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].set_title(f"Precision-Recall ({model_name})")
    axes[1].legend(loc="lower left")

    fig.tight_layout()
    fig.savefig(out_dir / f"{model_name}_roc_pr_curves.png", dpi=300)
    plt.close(fig)


def export_shap_importance(classifier: CrypticSiteMLClassifier, X: pd.DataFrame, out_path: Path) -> None:
    try:
        import shap
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("SHAP is required to export feature importance plot.") from exc

    transformed = classifier.best_estimator_.named_steps["imputer"].transform(X)
    model = classifier.best_estimator_.named_steps["classifier"]
    explainer = shap.TreeExplainer(model)
    values = explainer.shap_values(transformed)
    if isinstance(values, list):
        values = values[1]

    plt.figure(figsize=(8, 5))
    shap.summary_plot(values, transformed, feature_names=list(FEATURE_COLUMNS), plot_type="bar", show=False)
    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=300)
    plt.close()


def evaluate_threshold_baseline(X: pd.DataFrame) -> np.ndarray:
    scorer = PocketScorer()
    scores = []
    for _, row in X.iterrows():
        scores.append(
            scorer.calculate_composite_score(
                volume=float(row["pocket_volume"]),
                depth=float(row["pocket_depth"]),
                sasa=float(row["sasa"]),
                basic_count=int(row["n_basic_residues"]),
                potential=None if pd.isna(row["electrostatic_potential"]) else float(row["electrostatic_potential"]),
            )
        )
    return np.asarray(scores)


def main() -> None:
    args = parse_args()
    args.work_dir.mkdir(parents=True, exist_ok=True)
    args.model_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_build_dataset:
        run_dataset_builder(args.dataset_csv, args.download_dir)

    pocket_df = extract_pocket_features(args.dataset_csv, args.download_dir, args.work_dir)
    if pocket_df.empty:
        raise RuntimeError("No pocket features were extracted; unable to train model.")

    X = pocket_df.loc[:, FEATURE_COLUMNS].copy()
    y = pocket_df["label"].astype(int).to_numpy()

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=args.random_state, stratify=y
    )

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=args.random_state)
    training_summaries: Dict[str, Dict[str, object]] = {}
    trained_models: Dict[str, CrypticSiteMLClassifier] = {}

    for model_type in ("random_forest", "xgboost"):
        clf = CrypticSiteMLClassifier(model_type=model_type, random_state=args.random_state)
        results = clf.fit(X_train, y_train)
        cv_scores = cross_val_predict(
            clf.best_estimator_, X_train.loc[:, FEATURE_COLUMNS], y_train, cv=cv, method="predict_proba", n_jobs=-1
        )[:, 1]

        training_summaries[model_type] = {
            **asdict(results),
            "cv_roc_auc": float(roc_auc_score(y_train, cv_scores)),
            "cv_pr_auc": float(average_precision_score(y_train, cv_scores)),
        }
        trained_models[model_type] = clf
        plot_curves_with_ci(y_train, cv_scores, args.work_dir, model_type)

    best_model_type = max(training_summaries, key=lambda name: training_summaries[name]["cv_pr_auc"])
    best_model = trained_models[best_model_type]

    model_path = args.model_dir / "cryptic_ip_classifier_v1.pkl"
    best_model.save(str(model_path))

    export_shap_importance(best_model, X_train.loc[:, FEATURE_COLUMNS], args.model_dir / "cryptic_ip_classifier_v1_shap.png")

    ml_test_scores = best_model.predict_proba(X_test.loc[:, FEATURE_COLUMNS])
    threshold_scores = evaluate_threshold_baseline(X_test.loc[:, FEATURE_COLUMNS])

    comparison = pd.DataFrame(
        [
            {
                "method": f"ML ({best_model_type})",
                "test_roc_auc": roc_auc_score(y_test, ml_test_scores),
                "test_pr_auc": average_precision_score(y_test, ml_test_scores),
            },
            {
                "method": "Threshold scoring",
                "test_roc_auc": roc_auc_score(y_test, threshold_scores),
                "test_pr_auc": average_precision_score(y_test, threshold_scores),
            },
        ]
    )
    comparison.to_csv(args.work_dir / "ml_vs_threshold_comparison.csv", index=False)
    (args.work_dir / "ml_vs_threshold_comparison.md").write_text(dataframe_to_markdown(comparison), encoding="utf-8")

    metadata = {
        "model_version": "v1",
        "trained_at_utc": datetime.now(timezone.utc).isoformat(),
        "dataset_csv": str(args.dataset_csv),
        "num_structures": int(pocket_df["pdb_id"].nunique()),
        "num_pockets": int(len(pocket_df)),
        "feature_columns": list(FEATURE_COLUMNS),
        "model_candidates": training_summaries,
        "selected_model_type": best_model_type,
        "selected_hyperparameters": training_summaries[best_model_type]["best_params"],
        "dataset_sha256": sha256_file(args.dataset_csv),
    }

    metadata_path = args.model_dir / "cryptic_ip_classifier_v1.metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    model_card = args.model_dir / "cryptic_ip_classifier_v1_model_card.md"
    model_card.write_text(
        "\n".join(
            [
                "# Cryptic IP Classifier v1",
                "",
                f"- Trained: {metadata['trained_at_utc']}",
                f"- Dataset: `{metadata['dataset_csv']}`",
                f"- Structures: {metadata['num_structures']}",
                f"- Pockets: {metadata['num_pockets']}",
                f"- Selected model: {best_model_type}",
                f"- CV ROC AUC: {training_summaries[best_model_type]['cv_roc_auc']:.3f}",
                f"- CV PR AUC: {training_summaries[best_model_type]['cv_pr_auc']:.3f}",
                "",
                "## Hyperparameters",
                "```json",
                json.dumps(training_summaries[best_model_type]["best_params"], indent=2),
                "```",
                "",
                "## Held-out benchmark",
                dataframe_to_markdown(comparison),
                "",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
